#!/bin/sh
#
# @name Gazebo team racer
#
# @type Quadrotor
#

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=team_racer}

param set-default SIM_GZ_EN 1

# CAD-derived motor positions in PX4 FRD coordinates. Motor numbering and
# yaw-moment signs intentionally retain the gz_x500 baseline.
param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 4

param set-default CA_ROTOR0_PX 0.0821160896
param set-default CA_ROTOR0_PY 0.0836499899
param set-default CA_ROTOR0_PZ 0.0035639400
param set-default CA_ROTOR0_KM 0.05

param set-default CA_ROTOR1_PX -0.0946606057
param set-default CA_ROTOR1_PY -0.0931267054
param set-default CA_ROTOR1_PZ 0.0035639400
param set-default CA_ROTOR1_KM 0.05

param set-default CA_ROTOR2_PX 0.0821160896
param set-default CA_ROTOR2_PY -0.0931267054
param set-default CA_ROTOR2_PZ 0.0035639400
param set-default CA_ROTOR2_KM -0.05

param set-default CA_ROTOR3_PX -0.0946606057
param set-default CA_ROTOR3_PY 0.0836499899
param set-default CA_ROTOR3_PZ 0.0035639400
param set-default CA_ROTOR3_KM -0.05

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104

param set-default SIM_GZ_EC_MIN1 150
param set-default SIM_GZ_EC_MIN2 150
param set-default SIM_GZ_EC_MIN3 150
param set-default SIM_GZ_EC_MIN4 150

param set-default SIM_GZ_EC_MAX1 1000
param set-default SIM_GZ_EC_MAX2 1000
param set-default SIM_GZ_EC_MAX3 1000
param set-default SIM_GZ_EC_MAX4 1000

# Temporary gz_x500 control baseline. Replace after mass and propulsion tests.
param set-default MPC_THR_HOVER 0.60
param set-default NAV_DLL_ACT 2
